package com.example.compose

import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFF1A1A2E)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFF16213E)
val md_theme_light_onPrimaryContainer = Color(0xFFE6E6FA)
val md_theme_light_secondary = Color(0xFF282846)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFF343a40)
val md_theme_light_onSecondaryContainer = Color(0xFFB0C4DE)
val md_theme_light_tertiary = Color(0xFF2E4053)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFF1F3A93)
val md_theme_light_onTertiaryContainer = Color(0xFFD5D8DC)
val md_theme_light_error = Color(0xFFB22222)
val md_theme_light_errorContainer = Color(0xFFFA8072)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF8B0000)
val md_theme_light_background = Color(0xFF1C1C1C)
val md_theme_light_onBackground = Color(0xFFE8E8E8)
val md_theme_light_surface = Color(0xFF1C1C1C)
val md_theme_light_onSurface = Color(0xFFE8E8E8)
val md_theme_light_surfaceVariant = Color(0xFF4B4B4B)
val md_theme_light_onSurfaceVariant = Color(0xFFD3D3D3)
val md_theme_light_outline = Color(0xFF696969)
val md_theme_light_inverseOnSurface = Color(0xFF1C1C1C)
val md_theme_light_inverseSurface = Color(0xFFE8E8E8)
val md_theme_light_inversePrimary = Color(0xFF4B0082)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_surfaceTint = Color(0xFF1A1A2E)
val md_theme_light_outlineVariant = Color(0xFF4B4B4B)
val md_theme_light_scrim = Color(0xFF000000)

val md_theme_dark_primary = Color(0xFF4B0082)
val md_theme_dark_onPrimary = Color(0xFFFFFFFF)
val md_theme_dark_primaryContainer = Color(0xFF301934)
val md_theme_dark_onPrimaryContainer = Color(0xFFDA70D6)
val md_theme_dark_secondary = Color(0xFF6A5ACD)
val md_theme_dark_onSecondary = Color(0xFFFFFFFF)
val md_theme_dark_secondaryContainer = Color(0xFF483D8B)
val md_theme_dark_onSecondaryContainer = Color(0xFFB0C4DE)
val md_theme_dark_tertiary = Color(0xFF4682B4)
val md_theme_dark_onTertiary = Color(0xFFFFFFFF)
val md_theme_dark_tertiaryContainer = Color(0xFF2E8B57)
val md_theme_dark_onTertiaryContainer = Color(0xFFD5D8DC)
val md_theme_dark_error = Color(0xFFB22222)
val md_theme_dark_errorContainer = Color(0xFFFA8072)
val md_theme_dark_onError = Color(0xFFFFFFFF)
val md_theme_dark_onErrorContainer = Color(0xFF8B0000)
val md_theme_dark_background = Color(0xFF1C1C1C)
val md_theme_dark_onBackground = Color(0xFFE8E8E8)
val md_theme_dark_surface = Color(0xFF1C1C1C)
val md_theme_dark_onSurface = Color(0xFFE8E8E8)
val md_theme_dark_surfaceVariant = Color(0xFF4B4B4B)
val md_theme_dark_onSurfaceVariant = Color(0xFFD3D3D3)
val md_theme_dark_outline = Color(0xFF696969)
val md_theme_dark_inverseOnSurface = Color(0xFF1C1C1C)
val md_theme_dark_inverseSurface = Color(0xFFE8E8E8)
val md_theme_dark_inversePrimary = Color(0xFF1A1A2E)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_surfaceTint = Color(0xFF4B0082)
val md_theme_dark_outlineVariant = Color(0xFF4B4B4B)
val md_theme_dark_scrim = Color(0xFF000000)

val seed = Color(0xFF1A1A2E)

